# Note: Base output directory of /public is assumed for static files
default: &default
  compile: false
  manifest: manifest.json
  # Used in your webpack configuration. Must be created in the
  # public_output_path folder

development:
  <<: *default
  dev_server:
    host: localhost
    port: 3000
    https: false
    # Can be enabled by export WEBPACKER_HMR=TRUE in env
    hot: false

  # generated files for development, in /public/webpack/development
  public_output_path: webpack/development

test:
  <<: *default
  # generated files for tests, in /public/webpack/test
  public_output_path: webpack/test

production:
  <<: *default
  # generated files for tests, in /public/webpack/production
  public_output_path: webpack/production
